### ISSUE TITLE
Исследовать источники данных для Яндекс.Карт

### ISSUE THREAD

**Issue by Bromles** [Bromles/spbstu-trkpo#5]
Яндекс.Карты для постановки кастомных маркеров требуют две координаты для каждого из них. Исследовать, откуда можно получить координаты больниц в автоматическом режиме

**Comment by KateBor** [comment]
От преподавателя было предложение посмотреть в сторону OpenStreetMaps для получения координат

**Comment by DariaDiurdeva** [comment]
Координаты можно вытянуть вместе с инфой о больнице  с АПИ горздрава, можно не юзать OpenStreetMaps

**Comment by KateBor** [comment]
Задача не актуальна, закрываю issue
