### ISSUE TITLE
Исправить минорные баги

### ISSUE THREAD

**Issue by KateBor** [Bromles/spbstu-trkpo#58]
Исправить:
1. Дублирование записей в табилце client
2. Добавить отображение фамилии в шапке
3. Перестать удалять записи из таблицы tracking
4. Поправить верстку

**Comment by DariaDiurdeva** [comment]
Баги: 
1) Ошибка в тексте на анонимке  

- нужную ВАМ больницу
- как только мы Увидим
- для пользования нашим сайтом, пожалуйста, зарегистрируйтесь по кнопке ВЫШЕ или в В ШАПКЕ(без сайта в конце)
